const float CROSSHAIR_WIDTH = 0.02f;
const float CROSSHAIR_HEIGHT = CROSSHAIR_WIDTH * (800.0f / 600.0f);
const float CROSSHAIR_THICKNESS = 0.004f;

const float crosshair_verticies[] = {
	-CROSSHAIR_WIDTH, -CROSSHAIR_THICKNESS, 0.0f,
	CROSSHAIR_WIDTH, -CROSSHAIR_THICKNESS, 0.0f,
	CROSSHAIR_WIDTH, CROSSHAIR_THICKNESS, 0.0f,
	CROSSHAIR_WIDTH, CROSSHAIR_THICKNESS, 0.0f,
	-CROSSHAIR_WIDTH, CROSSHAIR_THICKNESS, 0.0f,
	-CROSSHAIR_WIDTH, -CROSSHAIR_THICKNESS, 0.0f,

	-CROSSHAIR_THICKNESS, CROSSHAIR_HEIGHT, 0.0f,
	-CROSSHAIR_THICKNESS, -CROSSHAIR_HEIGHT, 0.0f,
	CROSSHAIR_THICKNESS, -CROSSHAIR_HEIGHT, 0.0f,
	CROSSHAIR_THICKNESS, -CROSSHAIR_HEIGHT, 0.0f,
	CROSSHAIR_THICKNESS, CROSSHAIR_HEIGHT, 0.0f,
	-CROSSHAIR_THICKNESS, CROSSHAIR_HEIGHT, 0.0f,
};
